### PR TITLE
emma_sprint18

### PR DESCRIPTION
**Pull request by e-vic**
Updated momentum unloading library. Updated test case file to work with recent changes in environment block. Test case has two options for rigid body dynamics block: original and corrected, if you're running the test case the corrected block works best, but both will run.

### CODE REVIEW

**Comment by tpreynolds** [comment]
@e-vic why include a test case with a dynamics block we know isn't fully correct? Maybe just include the right dynamics

**Comment by e-vic** [comment]
Good point. @MathiasKerman when you do the check, could you delete the old dynamics block and just keep the modified one? Thanks!

**Comment by MathiasKerman** [comment]
I'm only seeing one dynamics block. Where do I switch between them?

**Comment by e-vic** [comment]
Sorry, rigid body dynamics**

**Comment by MathiasKerman** [comment]
Something's wonky!

**Pull request closed without merging**
