### PR TITLE
Tested gyro_processing, changed noise parameters, first pass at rotat…

### PR DESCRIPTION
**Pull request by scrice**
…ional visualization (more work needed)

### CODE REVIEW

**Comment by e-vic** [comment]
I'll review this tonight!

**Comment by e-vic** [comment]
Sorry, didn't get to it until now... @scrice I'm not sure I'm the best one to review this, as my experience with Kalman filters is minimal (i.e. used one for the first time last week). I can certainly look through it, but I don't think I know enough to catch any errors if they are there

**Comment by MathiasKerman** [comment]
The only thing Sean changed in the Kalman filter was the parameters for the gyro noise based off of the latest test data.

**Comment by e-vic** [comment]
Okay... sorry if this is naive of me, but how would I double check that? Compare with the test data? I can also just ask Sean tomorrow

**Comment by MathiasKerman** [comment]
Nah you're good. The ARW parameters are in the document I shared on slack/ADCS-sensors. Just check that they match the ones in fsw_params.

**Comment by e-vic** [comment]
@scrice the updated noise parameters check out, but your gyro processing test init file calls the gps processing test simulink file, but that's just in a test file, so it should be fine?

**Comment by tpreynolds** [comment]
@e-vic @scrice The gyro test gives me some bad stuff when I run the simulink file. Also the matlab script for it doesn't work (Emma's right, it references the wrong library & doesn't look updated).

**Comment by scrice** [comment]
@tpreynolds For some reason I didn't get any notifications about this thread and thought it was resolved. What bad stuff are you seeing when running the simulink file? I wasn't actually using the matlab script for testing, that's why it is still the GPS testing one, I will update it.

**Pull request merged**
